### PR TITLE
Added s390x support

### PR DESCRIPTION
**Pull request by mayurwaghmode**
Signed-off-by: mayurwaghmode <waghmodemayur17@gmail.com>

### CODE REVIEW

**Comment by MartinBasti** [comment]
Hello, I see many PR from you for the same issue.
image


Could you please rebase and force push to your branch, instead of opening new PRs?

https://blog.verslu.is/git/git-rebase/

**Comment by chmeliik** [comment]
@mayurwaghmode would you be able to sign-off with your own username and email? I suspect [root@juiciest1.fyre.ibm.com](mailto:root@juiciest1.fyre.ibm.com) is not it :D

**Comment by mayurwaghmode** [comment]
> @mayurwaghmode would you be able to sign-off with your own username and email? I suspect [root@juiciest1.fyre.ibm.com](mailto:root@juiciest1.fyre.ibm.com) is not it :D
> 
> (doesn't need to be your personal email, just something that's you and not root@some-vm)

Done

**Comment by MartinBasti** [comment]
you have to change it in commit, not in comment here

```
git commit --amend -s --author 'Author Name <author.name@mail.com>' --no-edit
git push --force
```
https://stackoverflow.com/questions/750172/how-to-change-the-author-and-committer-name-and-e-mail-of-multiple-commits-in-gi

**Comment by mayurwaghmode** [comment]
> you have to change it in commit, not in comment here
> 
> ```
> git commit --amend -s --author 'Author Name <author.name@mail.com>' --no-edit
> git push --force
> ```
> 
> https://stackoverflow.com/questions/750172/how-to-change-the-author-and-committer-name-and-e-mail-of-multiple-commits-in-gi

Thanks @MartinBasti!
Done now!

**Comment by MartinBasti** [comment]
`Signed-off-by: root <root@juiciest1.fyre.ibm.com>`

I still see this :D

**Comment by MartinBasti** [comment]
probably just `git commit --amend` and update it manually. Have you configured your name and email to git config?

**Comment by mayurwaghmode** [comment]
@MartinBasti ok now?

**Comment by MartinBasti** [comment]
image
Not yet, keep just valid entry

**Comment by mayurwaghmode** [comment]
@MartinBasti Done now :)

**Review by MartinBasti — APPROVED** [review]

**Pull request merged**
